version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ifitv-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ifitv-net

  backend:
    build: ./backend
    container_name: ifitv-backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - ifitv-net

  frontend:
    build: ./frontend
    container_name: ifitv-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ifitv-net

volumes:
  mysql_data:

networks:
  ifitv-net:
