# Generated by Django 5.2.1 on 2025-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('subgenre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cast', models.TextField()),
                ('age_rating', models.CharField(max_length=50)),
                ('thumbnail', models.TextField()),
            ],
        ),
    ]
