# Generated by Django 5.2.1 on 2025-05-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='subgenre',
        ),
        migrations.AlterField(
            model_name='content',
            name='age_rating',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ContentSubgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.subgenre')),
            ],
            options={
                'unique_together': {('content', 'subgenre')},
            },
        ),
        migrations.AddField(
            model_name='content',
            name='subgenres',
            field=models.ManyToManyField(through='contents.ContentSubgenre', to='contents.subgenre'),
        ),
    ]
