# Generated by Django 5.2.1 on 2025-05-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_subgenre_remove_content_subgenre_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='contents',
        ),
        migrations.AlterModelTable(
            name='contentsubgenre',
            table='content_subgenres',
        ),
        migrations.AlterModelTable(
            name='subgenre',
            table='subgenres',
        ),
    ]
