# Generated by Django 5.2.1 on 2025-05-14 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_content_table_alter_contentsubgenre_table_and_more'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_contents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_genres',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileLikedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_contents', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'content')},
            },
        ),
        migrations.CreateModel(
            name='ProfilePreferredSubgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_subgenres', to='profiles.profile')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.subgenre')),
            ],
            options={
                'unique_together': {('profile', 'subgenre')},
            },
        ),
    ]
